# Generated by Django 4.1 on 2022-10-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='password',
            field=models.CharField(max_length=5),
        ),
    ]
